
version: '3'
services:
  app:
    container_name: restaurant_laravel  
    build: ./docker/php
    volumes:
      - ./laravel-project:/var/www
      - /app/node_modules
    command: bash -c "cd /var/www && cron && php-fpm"
  nginx:
    image: nginx 
    container_name: nginx
    ports:
      - 8001:80 
    volumes:
      - ./laravel-project:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
  db:
    image: mysql:8.0.36
    container_name: db_restaurant
    environment: 
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database 
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+9:00
    volumes:  
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf 
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin_restaurant
    image: phpmyadmin
    environment:
    - PMA_USER=root
    - PMA_PASSWORD=password
    - TZ=Asia/Tokyo
    ports:
    - 8080:80
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"